test_python:
  stage: test
  image: python:3.7
  script:
    - cd python/
    - pip install Cython
    - BUILD_CYTHON=1 python setup.py develop
    - python tests.py

test_rust:
  stage: test
  image: rust:1.45.2
  script:
    - cd rust
    - cargo test
    - diff -q /tmp/test.db ../python/test.db
